import { NextRequest, NextResponse } from 'next/server';
import { sb } from '../../../../lib/supabase';
export const dynamic = 'force-dynamic';

async function sendTelegram(token: string, chatId: string, text: string) {
  if (!token || !chatId) return false;
  try {
    const res = await fetch(`https://api.telegram.org/bot${token}/sendMessage`, {
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      body: JSON.stringify({ chat_id: chatId, text, parse_mode: 'HTML' }),
    });
    return res.ok;
  } catch { return false; }
}

export async function POST(req: NextRequest) {
  const { approved_trades = [], biases = {}, risk = {} } = await req.json().catch(()=>({}));

  // Get Telegram config from Supabase
  const { data: cfg } = await sb.from('telegram_config').select('*').eq('id',1).single();
  const token  = cfg?.bot_token  ?? '';
  const chatId = cfg?.chat_id    ?? '';
  const active = cfg?.active     ?? false;

  let sent = 0;

  if (active && token && chatId) {
    // Send approved trade alerts
    for (const trade of approved_trades.slice(0,3)) {
      const dir = trade.direction === 'buy' ? '🟢 LONG' : '🔴 SHORT';
      const msg = `<b>🤖 VECTOR AI — Trade Signal</b>

${dir} <b>${trade.symbol}</b>
Score: <b>${trade.setup_score}/10</b> (${trade.confidence})
Reason: ${trade.primary_reason}
Entry: ${trade.entry_zone}
Target: ${trade.target}
Invalidation: ${trade.invalidation}
Risk: ${trade.risk_adjustment}

<i>Generated by VECTOR Intelligence</i>`;
      const ok = await sendTelegram(token, chatId, msg);
      if (ok) sent++;
    }

    // Daily briefing check (08:00 UTC)
    const now = new Date();
    const h = now.getUTCHours();
    const m = now.getUTCMinutes();
    if (h === 8 && m < 30) {
      const biasLines = Object.entries(biases)
        .map(([sym,b]) => `• ${sym}: ${b}`)
        .join('\n');
      const msg = `<b>🌅 VECTOR Daily Briefing — ${now.toUTCString().slice(0,16)}</b>

<b>Market Bias:</b>
${biasLines || '• Scanning...'}

<b>Portfolio:</b>
Heat: ${risk.portfolio_heat?.toFixed(1) ?? 0}%
Daily P&L: $${risk.daily_pnl?.toFixed(0) ?? 0}
Open: ${risk.open_positions ?? 0} positions

<b>Trading:</b> ${risk.can_trade ? '✅ Active' : `⛔ Paused — ${risk.blocked_reason}`}

<i>VECTOR Intelligence</i>`;
      const ok = await sendTelegram(token, chatId, msg);
      if (ok) sent++;
    }
  }

  return NextResponse.json({ sent, has_telegram: !!(token && chatId && active) });
}
