name: Deploy to Vercel

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm

      - name: Install deps
        run: npm ci --legacy-peer-deps

      - name: Deploy to Vercel
        uses: amondnet/vercel-action@v25
        with:
          vercel-token: ${{ secrets.VERCEL_TOKEN }}
          vercel-org-id: team_4K6zNXa5SgKXnomXu9yP9xge
          vercel-project-id: prj_X8Wum9saUBQ7LQlDTnnH32yYNpHz
          vercel-args: '--prod'
          working-directory: ./
